### ISSUE TITLE
Installation within codyco-superbuild?

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology-playground/icub-gazebo-wholebody#11]
Dear all

in the readme it is suggested to use this alias:
```
alias gazebo_standup="cd $CODYCO_SUPERBUILD_ROOT/build/install/share/gazebo/worlds/icub_standup_world && gazebo -slibgazebo_yarp_clock.so
```
However I just installed the codyco-superbuild and icub-gazebo-wholebody is not installed with it. So my alias is simply:
```
alias gazebo_standup="cd $code/icub-gazebo-wholebody/worlds/icub_standup_world && gazebo -slibgazebo_yarp_clock.so"
```

How can we enable the compilation within the codyco-superbuild?

**Comment by gabrielenava** [comment]
In order to install this repo with codyco-superbuild, it is necessary to enable the option `CODYCO_USES_GAZEBO` in the `codyco-superbuild/build` directory. Just type `ccmake ../` inside the build directory and then press `t` to make the option visible (it is an advanced option). The repo will be downloaded and installed as long as `icub-gazebo` and `gazebo-yarp-plugins`

**Comment by francesco-romano** [comment]
Furthermore @gabrielenava please modify the documentation to use the variable `GAZEBO_RESOURCE_PATH` instead of the alias

**Comment by gabrielenava** [comment]
done at https://github.com/robotology-playground/icub-gazebo-wholebody/commit/5d1d542ee751d9e1c0910d607c18330f4b28b8a6. Closing this issue
