### ISSUE TITLE
Folders containing world files are not properly added to the GAZEBO_RESOURCE_PATH when installing this repo inside the superbuild

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/icub-gazebo-wholebody#24]
According to the [documentation](https://github.com/robotology/icub-gazebo-wholebody/blob/master/worlds/icub_standup_world/README.md) of this repo, it is possible to load a `world` file in Gazebo by running in a terminal `gazebo NAME_OF_THE_WORLD_FILE`, provided that the folder where the world file is located has been added to the `GAZEBO_RESOURCE_PATH`.

I use this repository inside the superbuild. and the `GAZEBO_RESOURCE_PATH` is generated using the [setup.sh](https://github.com/robotology/robotology-superbuild/blob/master/cmake/template/setup.sh.in) file. I noted that the path that is added to the `GAZEBO_RESOURCE_PATH` is `<prefix>/gazebo/worlds`. However, each `world` file in the repo is stored in a separate folder, named, e.g. `icub_standup_world`. Therefore in order to use for example the standup world file in Gazebo it is necessary to run `gazebo icub_standup_world/icub_standup_world`, where the first `icub_standup_world` is the folder name and the second the file name. Not doing this result in Gazebo crashing with bad alloc error and no further explanations.

**Comment by traversaro** [comment]
Related comment: https://github.com/robotology/icub-gazebo-wholebody/pull/23#discussion_r235675935 . 
Do you think we should adapt the documentation to mention that you need to run the world with its directory name, or we should shift to just install all the world in a flat directory?

> Not doing this result in Gazebo crashing with bad alloc error and no further explanations.

This is definitely a gazebo bug.

**Comment by lrapetti** [comment]
> or we should shift to just install all the world in a flat directory?

I think the advantage of having worlds inside directories in term organization is to have in the same folder:
- documentation regarding the usage of the world
- configuration files (in order to load the configuration file within the world `.sdf` you can use `file://path/to/file/from/GAZEBO_RESOURCE_PATH`)

> > Not doing this result in Gazebo crashing with bad alloc error and no further explanations.
> 
> This is definitely a gazebo bug. 
> 

I am not experiencing Gazebo crashing, I am getting `Error parsing XML in file` (when Gazebo tries to launch the folder instead of the world).

In case we decide to maintain the folders, in general I think it is better to have distinction among the name of the world and folder like in `icub_simple_fixed_world/icub_simple_fixed.world`, or alternatively `icub_simple_fixed/icub_simple_fixed.world`(now some worlds use `_world` both for the folder and the file e.g. `icub_seesaw_world/icub_seesaw_world`).

**Comment by gabrielenava** [comment]
I agree on having different names for folders and files. I think the quickest fix is to change the documentation, I would like to keep the same structure both in the install folder and in the source folder, so that the path will be consistent even if the user decides to not install the repo.

**Comment by gabrielenava** [comment]
I fixed the issue in `master` and `devel` branch. Closing.
