### ISSUE TITLE
Reset causes icub pose to change

### ISSUE THREAD

**Issue by rlober** [robotology-playground/icub-gazebo-wholebody#5]
So when I start `icub_chair_world` everything is fine and looks like this:

![start_icub_chair](https://cloud.githubusercontent.com/assets/3417094/23461074/9ca8ee84-fe88-11e6-937b-449976489750.png)

However, when I reset the world: `ctrl+r` the icub model changes its world position to this:

![reset_icub_chair](https://cloud.githubusercontent.com/assets/3417094/23461078/9f23582a-fe88-11e6-98b4-6c45f044f809.png)

Here is a zoom:
![zoom](https://cloud.githubusercontent.com/assets/3417094/23461071/9a755ab2-fe88-11e6-92d1-9a2957273317.png)

Not sure where this bug comes from but it has been happening since the `icub_chair` branch of `icub-gazebo` days.

**Comment by rlober** [comment]
ping

@gabrielenava 
@traversaro 
@francesco-romano

**Comment by gabrielenava** [comment]
I didn't fix the problem, but I think I figured out why it happens. The reason is the following line in [icub_chair_world](https://github.com/robotology-playground/icub-gazebo-wholebody/tree/master/worlds/icub_chair_world) file:

~~~
<model name='iCub'>
     <include>
      <uri>model://icub_chair</uri>
      <pose> 0 0 0 0 0 0 </pose>     
      </include>
</model>  
~~~

more precisely, the iCub base frame pose is:

~~~
      <pose> 0 0 0 0 0 0 </pose> 
~~~

I'm not sure what's going on when someone presses `ctrl+r`, but I suppose Gazebo changes the base frame pose to [0 0 0 0 0 0]. That's why iCub becomes part of the chair. 

So, I copy-pasted the base frame pose from this line in the same `icub_chair_world` file:

~~~
   <link name='root_link'>
          <pose frame=''>-0.077649 0.000965 0.389694 -8e-06 0.036487 -3.14094</pose>
~~~

But now when I open the world the robot is oriented in the opposite direction:

![screenshot from 2017-03-03 14-55-08](https://cloud.githubusercontent.com/assets/12396934/23553556/91341d7c-0021-11e7-9613-50215ea220c4.png)


and if I press `ctrl+r` it goes now in the right position:

![screenshot from 2017-03-03 14-55-24](https://cloud.githubusercontent.com/assets/12396934/23553559/968a951c-0021-11e7-88fb-be534b66b4af.png)

And I still don't know why this happens. I think that orientation must be changed somewhere else.

**Comment by traversaro** [comment]
I think the additional rotation it is due to https://github.com/robotology/icub-gazebo/blob/master/icub/icub.sdf#L4 .

**Comment by rlober** [comment]
PR should fix it: https://github.com/robotology-playground/icub-gazebo-wholebody/pull/6

Not sure if there will be repercussions for the other worlds though. Also the initial view changes to the default gazebo perspective
