### ISSUE TITLE
Contacts on the chair are in the opposite direction

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/icub-gazebo-wholebody#7]
![screenshot from 2017-03-09 13-45-01](https://cloud.githubusercontent.com/assets/12396934/23750753/b737032a-04ce-11e7-9811-d685a0278706.png)

as in the image. Since the robot is not jumping away, I think it may be a visualization problem or a frame with wrong orientation 

CC @rlober

**Comment by rlober** [comment]
Well it looks like the normal is pulled from the contact topic: https://bitbucket.org/osrf/gazebo/src/cd526975bc8bdf3813e0600e3ece180870602471/gazebo/rendering/ContactVisual.cc?at=default&fileviewer=file-view-default#ContactVisual.cc-101

And taking a look at it with `gz topic -e /gazebo/default/physics/contacts`

you get output like: 
```
wrench {
    body_1_name: "chair::high_part::collision_high"
    body_1_id: 175
    body_2_name: "iCub::l_upper_leg::l_upper_leg_collision"
    body_2_id: 28
    body_1_wrench {
      force {
        x: -0.20408953945880551
        y: -2.251468314189732
        z: -95.0155083855776
      }
      torque {
        x: -8.5008340899648527
        y: 2.3728687651796689
        z: -0.037967565352136572
      }
    }
    body_2_wrench {
      force {
        x: 94.916552570345829
        y: 3.769660080872729
        z: -3.1137287799575795
      }
      torque {
        x: -0.19327655310875769
        y: -0.1167078391959917
        z: -6.0329894874660823
      }
    }
  }
  time {
    sec: 110
    nsec: 312000000
  }
  world: "default"
}
time {
  sec: 110
  nsec: 312000000
}
```

So the problem is basically that body 1 is the chair and not iCub and this is because of iCub being included before the chair in the world file: https://github.com/robotology-playground/icub-gazebo-wholebody/blob/master/worlds/icub_chair_world/icub_chair_world#L15-L23

So if you include iCub after the chair:
```
    <!-- Chair for sittin' on -->
    <include>
        <uri>model://chair</uri>
    </include>

    <!-- iCub in the sitting position -->
    <include>
    <uri>model://icub_chair</uri>
    </include>
  </world>
</sdf>
```

The bodies switch and the contact normals are flipped.
![default_gzclient_camera 1 -2017-03-09t14_09_32 923034](https://cloud.githubusercontent.com/assets/3417094/23751531/19b82bf2-04d2-11e7-81d3-c294a33f7a7d.jpg)


Submitted fix in PR: https://github.com/robotology-playground/icub-gazebo-wholebody/pull/8

**Comment by rlober** [comment]
Looks like there is an extra spurious contact on the `r_upper_thigh` - this may be improved with a bit of re-positioning.

**Comment by gabrielenava** [comment]
tested and working, thanks!

**Comment by rlober** [comment]
:+1:
